### ISSUE TITLE
Release a stable version

### ISSUE THREAD

**Issue by yordis** [virtualroot/asdf-opentofu#12]
**Describe the bug**

Right now when doing `asdf list-all opentofu` only alpha versions are displayed, but there seems to be a `v1.0.0` in GitHub.

So I am not sure if the package is actually in `alpha` or it needs to be released properly.

**Steps to reproduce**

1. `asdf plugin add opentofu https://github.com/virtualroot/asdf-opentofu.git`
2. `asdf list-all opentofu`
3. Output:
     ```
     1.6.0-alpha1
     1.6.0-alpha2
     1.6.0-alpha3
     ```

**Expected behavior**

Stable release

**Screenshots**

![Screenshot 2023-11-08 at 5 35 16 PM](https://github.com/virtualroot/asdf-opentofu/assets/4237280/65056161-da7c-4077-bc46-88d10ee8b092)

**Comment by virtualroot** [comment]
Hi @yordis 

These are two different things.

When you see v1.0.0, it's referring to the asdf [plugin version](https://github.com/virtualroot/asdf-opentofu/releases/tag/v1.0.0) that can be updated with `asdf plugin update opentofu`

The asdf plugin gets the list of official opentofu releases from https://github.com/opentofu/opentofu/releases, and you should see the same versions from that list in the `asdf list-all opentofu` output.

**Comment by yordis** [comment]
🤦🏻 ... my apologies ... 🤦🏻
