### ISSUE TITLE
Add support for legacy parsing of main.tf

### ISSUE THREAD

**Issue by hinricht** [virtualroot/asdf-opentofu#32]
**Is your feature request related to a problem? Please describe.**

We'd like to use the `main.tf`/`main.tofu` file to pin the opentofu version, just like the [terraform plugin](https://github.com/asdf-community/asdf-hashicorp) does (i.e. https://github.com/asdf-community/asdf-hashicorp/blob/master/bin/parse-legacy-file).

See also the [legacy version files documentaion](https://mise.jdx.dev/configuration.html#legacy-version-files)

**Describe the solution you'd like**

We'd like the plugin to be able to 

- parse main.tf for an opentofu version contraint
- parse .opentofu-version for an  opentofu version contraint (although not that important to us, but this would make it feature-complete to asdf-hashicorp

**Describe alternatives you've considered**

- Pinning the opentofu version in `.mise.toml` is an option, although this leads to 2 places where the tofu version is pinned (`.mise.toml` and `main.tofu`)

**Additional context**

None

**Comment by virtualroot** [comment]
Hi @hinricht :wave: many thanks for opening this feature request.

I'm happy to accept a PR if you and others are willing to resolve any bugs that may appear after the feature is released.

Currently, I do not use `mise` or `legacy_version_file`, and I do not have time to maintain it after the release.

wdyt?

**Comment by hinricht** [comment]
@virtualroot Nice, I'll see when I can work on this, and will create a PR.

**Comment by hinricht** [comment]
Here it is, hope it works!

**Comment by hinricht** [comment]
Btw, I'm using mise and noticed that with this change, mise is able to set the tofu version from a main.tofu. but not from a file with a different name (even when I export the ASDF_OPENTOFU_VERSION_FILE env var to this file name).
I checked with the asdf-terradform plugin and it's the same.

Therefore I created a mise issue to track this error: jdx/mise#2602

Just fyi.

**Comment by virtualroot** [comment]
Thanks for the heads-up!
