### ISSUE TITLE
Verifying checksums

### ISSUE THREAD

**Issue by virtualroot** [virtualroot/asdf-opentofu#4]
`tofu` releases are coming out with a `SHA256SUMS` file. Use it to verify the checksum of the zip file.

**Comment by eliecharra** [comment]
Hey @virtualroot, may I take this one if you are not already on it?

**Comment by virtualroot** [comment]
> Hey @virtualroot, may I take this one if you are not already on it? 

@eliecharra it's all yours!

Thanks! 🙇

**Comment by virtualroot** [comment]
Oh, you are way ahead of me! 

I overlooked the linked open PR on my phone.

I'll quickly go through it on Monday. 👍

**Comment by eliecharra** [comment]
Sure thing! No hurry at all 😃
